export const CALL = 'CALL'
export const CALLING = 'CALLING'
export const CALL_CONNECTED = 'CALL_CONNECTED'
export const CALL_DISCONNECTED = 'CALL_DISCONNECTED'
export const CALL_Failed = 'CALL_Failed'

export const CLIENT_INITED = 'CLIENT_INITED'

export const CLIENT_LOGINING = 'CLIENT_LOGINING'
export const CLIENT_AUTH_RESULT = 'CLIENT_AUTH_RESULT'

export const CLIENT_CONNECTING = 'CLIENT_CONNECTING'
export const CLIENT_CONNECTED = 'CLIENT_CONNECTED'
export const CLIENT_CONNECTION_FAILED = 'CLIENT_CONNECTION_FAILED'
export const CLIENT_CONNECTION_CLOSED = 'CLIENT_CONNECTION_CLOSED'